version: '3'
services:
  # es-server
  es:
    build: ./docker/es
    container_name: elasticsearch_sample
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana_sample
    environment:
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_URL: http://elasticsearch_sample:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  # mysql
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_DATABASE=sample_project
    build: ./docker/mysql
    ports:
      - "3306:3306"
  # rails
  rails:
    build: .
    # command: scripts/start-server.sh
    volumes:
      - .:/app
      - vendor_bundle:/app/vendor/bundle
    ports:
      - "3003:3000"
    links:
      - db
      - es
    environment:
      - RAILS_DATABASE_USERNAME=root
      - RAILS_DATABASE_PASSWORD=docker
      - RAILS_DATABASE_NAME=sample_project
      - RAILS_DATABASE_HOST=db
    tty: true
    stdin_open: true

volumes:
  esdata1:
    driver: local
  vendor_bundle:
    driver: local
